var annotated_dup =
[
    [ "bio", "namespacebio.html", [
      [ "custom", "namespacebio_1_1custom.html", [
        [ "alphabet", "structbio_1_1custom_1_1alphabet.html", null ],
        [ "alphabet< char_type >", "structbio_1_1custom_1_1alphabet_3_01char__type_01_4.html", null ],
        [ "alphabet< uint_type >", "structbio_1_1custom_1_1alphabet_3_01uint__type_01_4.html", null ]
      ] ],
      [ "views", "namespacebio_1_1views.html", [
        [ "deep", "classbio_1_1views_1_1deep.html", "classbio_1_1views_1_1deep" ]
      ] ],
      [ "aa10li", "classbio_1_1aa10li.html", "classbio_1_1aa10li" ],
      [ "aa10murphy", "classbio_1_1aa10murphy.html", "classbio_1_1aa10murphy" ],
      [ "aa20", "classbio_1_1aa20.html", "classbio_1_1aa20" ],
      [ "aa27", "classbio_1_1aa27.html", "classbio_1_1aa27" ],
      [ "aligned_allocator", "classbio_1_1aligned__allocator.html", "classbio_1_1aligned__allocator" ],
      [ "alphabet_base", "classbio_1_1alphabet__base.html", "classbio_1_1alphabet__base" ],
      [ "alphabet_base< derived_type, 1ul, char_t >", "classbio_1_1alphabet__base_3_01derived__type_00_011ul_00_01char__t_01_4.html", "classbio_1_1alphabet__base_3_01derived__type_00_011ul_00_01char__t_01_4" ],
      [ "alphabet_proxy", "classbio_1_1alphabet__proxy.html", "classbio_1_1alphabet__proxy" ],
      [ "alphabet_tuple_base", "classbio_1_1alphabet__tuple__base.html", "classbio_1_1alphabet__tuple__base" ],
      [ "alphabet_variant", "classbio_1_1alphabet__variant.html", "classbio_1_1alphabet__variant" ],
      [ "aminoacid_base", "classbio_1_1aminoacid__base.html", "classbio_1_1aminoacid__base" ],
      [ "aminoacid_empty_base", "structbio_1_1aminoacid__empty__base.html", null ],
      [ "bitcompressed_vector", "classbio_1_1bitcompressed__vector.html", "classbio_1_1bitcompressed__vector" ],
      [ "cigar", "classbio_1_1cigar.html", "classbio_1_1cigar" ],
      [ "cigar_op", "classbio_1_1cigar__op.html", "classbio_1_1cigar__op" ],
      [ "concatenated_sequences", "classbio_1_1concatenated__sequences.html", "classbio_1_1concatenated__sequences" ],
      [ "const_reference", "structbio_1_1const__reference.html", null ],
      [ "difference_type", "structbio_1_1difference__type.html", null ],
      [ "dna15", "classbio_1_1dna15.html", "classbio_1_1dna15" ],
      [ "dna3bs", "classbio_1_1dna3bs.html", "classbio_1_1dna3bs" ],
      [ "dna4", "classbio_1_1dna4.html", "classbio_1_1dna4" ],
      [ "dna5", "classbio_1_1dna5.html", "classbio_1_1dna5" ],
      [ "dot_bracket3", "classbio_1_1dot__bracket3.html", "classbio_1_1dot__bracket3" ],
      [ "dssp9", "classbio_1_1dssp9.html", "classbio_1_1dssp9" ],
      [ "dynamic_bitset", "classbio_1_1dynamic__bitset.html", "classbio_1_1dynamic__bitset" ],
      [ "function_traits< std::function< return_t(args_t...)> >", "structbio_1_1function__traits_3_01std_1_1function_3_01return__t_07args__t_8_8_8_08_4_01_4.html", "structbio_1_1function__traits_3_01std_1_1function_3_01return__t_07args__t_8_8_8_08_4_01_4" ],
      [ "gap", "classbio_1_1gap.html", "classbio_1_1gap" ],
      [ "invalid_char_assignment", "structbio_1_1invalid__char__assignment.html", "structbio_1_1invalid__char__assignment" ],
      [ "is_constexpr_default_constructible", "structbio_1_1is__constexpr__default__constructible.html", "structbio_1_1is__constexpr__default__constructible" ],
      [ "is_constexpr_default_constructible< t >", "structbio_1_1is__constexpr__default__constructible_3_01t_01_4.html", null ],
      [ "mask", "classbio_1_1mask.html", "classbio_1_1mask" ],
      [ "masked", "classbio_1_1masked.html", "classbio_1_1masked" ],
      [ "nucleotide_base", "classbio_1_1nucleotide__base.html", "classbio_1_1nucleotide__base" ],
      [ "phred42", "classbio_1_1phred42.html", "classbio_1_1phred42" ],
      [ "phred63", "classbio_1_1phred63.html", "classbio_1_1phred63" ],
      [ "phred68legacy", "classbio_1_1phred68legacy.html", "classbio_1_1phred68legacy" ],
      [ "pod_tuple", "structbio_1_1pod__tuple.html", "structbio_1_1pod__tuple" ],
      [ "pod_tuple< type0 >", "structbio_1_1pod__tuple_3_01type0_01_4.html", "structbio_1_1pod__tuple_3_01type0_01_4" ],
      [ "pod_tuple< type0, types... >", "structbio_1_1pod__tuple_3_01type0_00_01types_8_8_8_01_4.html", "structbio_1_1pod__tuple_3_01type0_00_01types_8_8_8_01_4" ],
      [ "qualified", "classbio_1_1qualified.html", "classbio_1_1qualified" ],
      [ "quality_base", "classbio_1_1quality__base.html", "classbio_1_1quality__base" ],
      [ "range_innermost_value", "structbio_1_1range__innermost__value.html", "structbio_1_1range__innermost__value" ],
      [ "reference", "structbio_1_1reference.html", null ],
      [ "remove_rvalue_reference", "structbio_1_1remove__rvalue__reference.html", "structbio_1_1remove__rvalue__reference" ],
      [ "rna15", "classbio_1_1rna15.html", "classbio_1_1rna15" ],
      [ "rna4", "classbio_1_1rna4.html", "classbio_1_1rna4" ],
      [ "rna5", "classbio_1_1rna5.html", "classbio_1_1rna5" ],
      [ "rvalue_reference", "structbio_1_1rvalue__reference.html", null ],
      [ "sam_dna16", "classbio_1_1sam__dna16.html", "classbio_1_1sam__dna16" ],
      [ "semialphabet_any", "classbio_1_1semialphabet__any.html", "classbio_1_1semialphabet__any" ],
      [ "size_type", "structbio_1_1size__type.html", null ],
      [ "small_string", "classbio_1_1small__string.html", "classbio_1_1small__string" ],
      [ "small_vector", "classbio_1_1small__vector.html", "classbio_1_1small__vector" ],
      [ "structured_aa", "classbio_1_1structured__aa.html", "classbio_1_1structured__aa" ],
      [ "structured_rna", "classbio_1_1structured__rna.html", "classbio_1_1structured__rna" ],
      [ "type_list", "structbio_1_1type__list.html", "structbio_1_1type__list" ],
      [ "value_type", "structbio_1_1value__type.html", null ],
      [ "wuss", "classbio_1_1wuss.html", "classbio_1_1wuss" ]
    ] ],
    [ "std", null, [
      [ "hash< alphabet_t >", "structstd_1_1hash_3_01alphabet__t_01_4.html", "structstd_1_1hash_3_01alphabet__t_01_4" ],
      [ "hash< bio::dynamic_bitset< cap > >", "structstd_1_1hash_3_01bio_1_1dynamic__bitset_3_01cap_01_4_01_4.html", "structstd_1_1hash_3_01bio_1_1dynamic__bitset_3_01cap_01_4_01_4" ],
      [ "hash< urng_t >", "structstd_1_1hash_3_01urng__t_01_4.html", "structstd_1_1hash_3_01urng__t_01_4" ],
      [ "tuple_element< i, t< types... > >", "structstd_1_1tuple__element_3_01i_00_01t_3_01types_8_8_8_01_4_01_4.html", "structstd_1_1tuple__element_3_01i_00_01t_3_01types_8_8_8_01_4_01_4" ],
      [ "tuple_element< i, tuple_t >", "structstd_1_1tuple__element_3_01i_00_01tuple__t_01_4.html", "structstd_1_1tuple__element_3_01i_00_01tuple__t_01_4" ],
      [ "tuple_size< t< types... > >", "structstd_1_1tuple__size_3_01t_3_01types_8_8_8_01_4_01_4.html", null ],
      [ "tuple_size< tuple_t >", "structstd_1_1tuple__size_3_01tuple__t_01_4.html", null ]
    ] ],
    [ "alphabet", "interfacebio_1_1alphabet.html", null ],
    [ "aminoacid_alphabet", "interfacebio_1_1aminoacid__alphabet.html", null ],
    [ "arithmetic", "interfacebio_1_1arithmetic.html", null ],
    [ "builtin_character", "interfacebio_1_1builtin__character.html", null ],
    [ "cereal_archive", "interfacebio_1_1cereal__archive.html", null ],
    [ "cereal_input_archive", "interfacebio_1_1cereal__input__archive.html", null ],
    [ "cereal_output_archive", "interfacebio_1_1cereal__output__archive.html", null ],
    [ "cereal_text_archive", "interfacebio_1_1cereal__text__archive.html", null ],
    [ "cerealisable", "interfacebio_1_1cerealisable.html", null ],
    [ "const_iterable_range", "interfacebio_1_1const__iterable__range.html", null ],
    [ "container", "interfacebio_1_1container.html", null ],
    [ "explicitly_convertible_to", "interfacebio_1_1explicitly__convertible__to.html", null ],
    [ "floating_point", "interfacebio_1_1floating__point.html", null ],
    [ "implicitly_convertible_to", "interfacebio_1_1implicitly__convertible__to.html", null ],
    [ "nucleotide_alphabet", "interfacebio_1_1nucleotide__alphabet.html", null ],
    [ "pair_like", "interfacebio_1_1pair__like.html", "interfacebio_1_1pair__like" ],
    [ "pseudo_random_access_iterator", "interfacebio_1_1pseudo__random__access__iterator.html", null ],
    [ "pseudo_random_access_range", "interfacebio_1_1pseudo__random__access__range.html", null ],
    [ "quality_alphabet", "interfacebio_1_1quality__alphabet.html", null ],
    [ "random_access_container", "interfacebio_1_1random__access__container.html", null ],
    [ "range_compatible", "interfacebio_1_1range__compatible.html", null ],
    [ "reservible_container", "interfacebio_1_1reservible__container.html", null ],
    [ "rna_structure_alphabet", "interfacebio_1_1rna__structure__alphabet.html", null ],
    [ "semialphabet", "interfacebio_1_1semialphabet.html", null ],
    [ "sequence", "interfacebio_1_1sequence.html", null ],
    [ "sequence_container", "interfacebio_1_1sequence__container.html", null ],
    [ "standard_layout", "interfacebio_1_1standard__layout.html", null ],
    [ "transformation_trait", "interfacebio_1_1transformation__trait.html", null ],
    [ "trivial", "interfacebio_1_1trivial.html", null ],
    [ "trivially_copyable", "interfacebio_1_1trivially__copyable.html", null ],
    [ "trivially_destructible", "interfacebio_1_1trivially__destructible.html", null ],
    [ "tuple_like", "interfacebio_1_1tuple__like.html", "interfacebio_1_1tuple__like" ],
    [ "unary_type_trait", "interfacebio_1_1unary__type__trait.html", null ],
    [ "weakly_assignable_from", "interfacebio_1_1weakly__assignable__from.html", null ],
    [ "writable_alphabet", "interfacebio_1_1writable__alphabet.html", null ],
    [ "writable_quality_alphabet", "interfacebio_1_1writable__quality__alphabet.html", null ],
    [ "writable_semialphabet", "interfacebio_1_1writable__semialphabet.html", null ]
];