var annotated_dup =
[
    [ "bio", "namespacebio.html", [
      [ "alphabet", "namespacebio_1_1alphabet.html", [
        [ "custom", "namespacebio_1_1alphabet_1_1custom.html", [
          [ "assign_char_to", "structbio_1_1alphabet_1_1custom_1_1assign__char__to.html", null ],
          [ "assign_phred_to", "structbio_1_1alphabet_1_1custom_1_1assign__phred__to.html", null ],
          [ "assign_rank_to", "structbio_1_1alphabet_1_1custom_1_1assign__rank__to.html", null ],
          [ "char_is_valid_for", "structbio_1_1alphabet_1_1custom_1_1char__is__valid__for.html", null ],
          [ "complement", "structbio_1_1alphabet_1_1custom_1_1complement.html", null ],
          [ "size", "structbio_1_1alphabet_1_1custom_1_1size.html", null ],
          [ "to_char", "structbio_1_1alphabet_1_1custom_1_1to__char.html", null ],
          [ "to_phred", "structbio_1_1alphabet_1_1custom_1_1to__phred.html", null ],
          [ "to_rank", "structbio_1_1alphabet_1_1custom_1_1to__rank.html", null ]
        ] ],
        [ "aa10li", "classbio_1_1alphabet_1_1aa10li.html", "classbio_1_1alphabet_1_1aa10li" ],
        [ "aa10murphy", "classbio_1_1alphabet_1_1aa10murphy.html", "classbio_1_1alphabet_1_1aa10murphy" ],
        [ "aa20", "classbio_1_1alphabet_1_1aa20.html", "classbio_1_1alphabet_1_1aa20" ],
        [ "aa27", "classbio_1_1alphabet_1_1aa27.html", "classbio_1_1alphabet_1_1aa27" ],
        [ "aminoacid_base", "classbio_1_1alphabet_1_1aminoacid__base.html", "classbio_1_1alphabet_1_1aminoacid__base" ],
        [ "aminoacid_empty_base", "structbio_1_1alphabet_1_1aminoacid__empty__base.html", null ],
        [ "base", "classbio_1_1alphabet_1_1base.html", "classbio_1_1alphabet_1_1base" ],
        [ "base< derived_type, 1ul, char_t >", "classbio_1_1alphabet_1_1base_3_01derived__type_00_011ul_00_01char__t_01_4.html", "classbio_1_1alphabet_1_1base_3_01derived__type_00_011ul_00_01char__t_01_4" ],
        [ "cigar", "classbio_1_1alphabet_1_1cigar.html", "classbio_1_1alphabet_1_1cigar" ],
        [ "cigar_op", "classbio_1_1alphabet_1_1cigar__op.html", "classbio_1_1alphabet_1_1cigar__op" ],
        [ "dna15", "classbio_1_1alphabet_1_1dna15.html", "classbio_1_1alphabet_1_1dna15" ],
        [ "dna16sam", "classbio_1_1alphabet_1_1dna16sam.html", "classbio_1_1alphabet_1_1dna16sam" ],
        [ "dna4", "classbio_1_1alphabet_1_1dna4.html", "classbio_1_1alphabet_1_1dna4" ],
        [ "dna5", "classbio_1_1alphabet_1_1dna5.html", "classbio_1_1alphabet_1_1dna5" ],
        [ "gap", "classbio_1_1alphabet_1_1gap.html", "classbio_1_1alphabet_1_1gap" ],
        [ "invalid_char_assignment", "structbio_1_1alphabet_1_1invalid__char__assignment.html", "structbio_1_1alphabet_1_1invalid__char__assignment" ],
        [ "mask", "classbio_1_1alphabet_1_1mask.html", "classbio_1_1alphabet_1_1mask" ],
        [ "masked", "classbio_1_1alphabet_1_1masked.html", "classbio_1_1alphabet_1_1masked" ],
        [ "nucleotide_base", "classbio_1_1alphabet_1_1nucleotide__base.html", "classbio_1_1alphabet_1_1nucleotide__base" ],
        [ "phred42", "classbio_1_1alphabet_1_1phred42.html", "classbio_1_1alphabet_1_1phred42" ],
        [ "phred63", "classbio_1_1alphabet_1_1phred63.html", "classbio_1_1alphabet_1_1phred63" ],
        [ "phred68legacy", "classbio_1_1alphabet_1_1phred68legacy.html", "classbio_1_1alphabet_1_1phred68legacy" ],
        [ "proxy_base", "classbio_1_1alphabet_1_1proxy__base.html", "classbio_1_1alphabet_1_1proxy__base" ],
        [ "qualified", "classbio_1_1alphabet_1_1qualified.html", "classbio_1_1alphabet_1_1qualified" ],
        [ "quality_base", "classbio_1_1alphabet_1_1quality__base.html", "classbio_1_1alphabet_1_1quality__base" ],
        [ "rna15", "classbio_1_1alphabet_1_1rna15.html", "classbio_1_1alphabet_1_1rna15" ],
        [ "rna4", "classbio_1_1alphabet_1_1rna4.html", "classbio_1_1alphabet_1_1rna4" ],
        [ "rna5", "classbio_1_1alphabet_1_1rna5.html", "classbio_1_1alphabet_1_1rna5" ],
        [ "semialphabet_any", "classbio_1_1alphabet_1_1semialphabet__any.html", "classbio_1_1alphabet_1_1semialphabet__any" ],
        [ "tuple_base", "classbio_1_1alphabet_1_1tuple__base.html", "classbio_1_1alphabet_1_1tuple__base" ],
        [ "variant", "classbio_1_1alphabet_1_1variant.html", "classbio_1_1alphabet_1_1variant" ]
      ] ],
      [ "meta", "namespacebio_1_1meta.html", [
        [ "is_type_specialisation_of", "structbio_1_1meta_1_1is__type__specialisation__of.html", null ],
        [ "is_type_specialisation_of< source_t, target_template >", "structbio_1_1meta_1_1is__type__specialisation__of_3_01source__t_00_01target__template_01_4.html", null ],
        [ "is_value_specialisation_of< source_t, target_template >", "structbio_1_1meta_1_1is__value__specialisation__of_3_01source__t_00_01target__template_01_4.html", null ],
        [ "overloaded", "structbio_1_1meta_1_1overloaded.html", "structbio_1_1meta_1_1overloaded" ],
        [ "pod_tuple", "structbio_1_1meta_1_1pod__tuple.html", "structbio_1_1meta_1_1pod__tuple" ],
        [ "pod_tuple< type0 >", "structbio_1_1meta_1_1pod__tuple_3_01type0_01_4.html", "structbio_1_1meta_1_1pod__tuple_3_01type0_01_4" ],
        [ "pod_tuple< type0, types... >", "structbio_1_1meta_1_1pod__tuple_3_01type0_00_01types_8_8_8_01_4.html", "structbio_1_1meta_1_1pod__tuple_3_01type0_00_01types_8_8_8_01_4" ],
        [ "priority_tag", "structbio_1_1meta_1_1priority__tag.html", null ],
        [ "priority_tag< 0 >", "structbio_1_1meta_1_1priority__tag_3_010_01_4.html", null ],
        [ "transfer_template_args_onto< source_template< source_arg_types... >, target_template >", "structbio_1_1meta_1_1transfer__template__args__onto_3_01source__template_3_01source__arg__types_a0c928784694c351c065f80d4d89b15d.html", "structbio_1_1meta_1_1transfer__template__args__onto_3_01source__template_3_01source__arg__types_a0c928784694c351c065f80d4d89b15d" ],
        [ "transfer_template_vargs_onto< source_template< source_varg_types... >, target_template >", "structbio_1_1meta_1_1transfer__template__vargs__onto_3_01source__template_3_01source__varg__type4e348813352083c94c53b6206e44e292.html", "structbio_1_1meta_1_1transfer__template__vargs__onto_3_01source__template_3_01source__varg__type4e348813352083c94c53b6206e44e292" ],
        [ "type_list", "structbio_1_1meta_1_1type__list.html", "structbio_1_1meta_1_1type__list" ],
        [ "valid_template_spec_or", "structbio_1_1meta_1_1valid__template__spec__or.html", "structbio_1_1meta_1_1valid__template__spec__or" ],
        [ "valid_template_spec_or< fallback_t, templ_t, spec_t... >", "structbio_1_1meta_1_1valid__template__spec__or_3_01fallback__t_00_01templ__t_00_01spec__t_8_8_8_01_4.html", "structbio_1_1meta_1_1valid__template__spec__or_3_01fallback__t_00_01templ__t_00_01spec__t_8_8_8_01_4" ],
        [ "vtag_t", "structbio_1_1meta_1_1vtag__t.html", "structbio_1_1meta_1_1vtag__t" ],
        [ "vtag_t< v, more_vs... >", "structbio_1_1meta_1_1vtag__t_3_01v_00_01more__vs_8_8_8_01_4.html", "structbio_1_1meta_1_1vtag__t_3_01v_00_01more__vs_8_8_8_01_4" ]
      ] ],
      [ "ranges", "namespacebio_1_1ranges.html", [
        [ "views", "namespacebio_1_1ranges_1_1views.html", [
          [ "deep", "classbio_1_1ranges_1_1views_1_1deep.html", "classbio_1_1ranges_1_1views_1_1deep" ]
        ] ],
        [ "aligned_allocator", "classbio_1_1ranges_1_1aligned__allocator.html", "classbio_1_1ranges_1_1aligned__allocator" ],
        [ "bitcompressed_vector", "classbio_1_1ranges_1_1bitcompressed__vector.html", "classbio_1_1ranges_1_1bitcompressed__vector" ],
        [ "concatenated_sequences", "classbio_1_1ranges_1_1concatenated__sequences.html", "classbio_1_1ranges_1_1concatenated__sequences" ],
        [ "dynamic_bitset", "classbio_1_1ranges_1_1dynamic__bitset.html", "classbio_1_1ranges_1_1dynamic__bitset" ],
        [ "range_innermost_value", "structbio_1_1ranges_1_1range__innermost__value.html", "structbio_1_1ranges_1_1range__innermost__value" ],
        [ "small_string", "classbio_1_1ranges_1_1small__string.html", "classbio_1_1ranges_1_1small__string" ],
        [ "small_vector", "classbio_1_1ranges_1_1small__vector.html", "classbio_1_1ranges_1_1small__vector" ]
      ] ]
    ] ],
    [ "std", null, [
      [ "hash< alphabet_t >", "structstd_1_1hash_3_01alphabet__t_01_4.html", "structstd_1_1hash_3_01alphabet__t_01_4" ],
      [ "hash< bio::ranges::dynamic_bitset< cap > >", "structstd_1_1hash_3_01bio_1_1ranges_1_1dynamic__bitset_3_01cap_01_4_01_4.html", "structstd_1_1hash_3_01bio_1_1ranges_1_1dynamic__bitset_3_01cap_01_4_01_4" ],
      [ "hash< urng_t >", "structstd_1_1hash_3_01urng__t_01_4.html", "structstd_1_1hash_3_01urng__t_01_4" ],
      [ "tuple_element< i, t< types... > >", "structstd_1_1tuple__element_3_01i_00_01t_3_01types_8_8_8_01_4_01_4.html", "structstd_1_1tuple__element_3_01i_00_01t_3_01types_8_8_8_01_4_01_4" ],
      [ "tuple_element< i, tuple_t >", "structstd_1_1tuple__element_3_01i_00_01tuple__t_01_4.html", "structstd_1_1tuple__element_3_01i_00_01tuple__t_01_4" ],
      [ "tuple_size< t< types... > >", "structstd_1_1tuple__size_3_01t_3_01types_8_8_8_01_4_01_4.html", null ],
      [ "tuple_size< tuple_t >", "structstd_1_1tuple__size_3_01tuple__t_01_4.html", null ]
    ] ],
    [ "alphabet", "interfacebio_1_1alphabet_1_1alphabet.html", null ],
    [ "aminoacid_alphabet", "interfacebio_1_1alphabet_1_1aminoacid__alphabet.html", null ],
    [ "arithmetic", "interfacebio_1_1meta_1_1arithmetic.html", null ],
    [ "back_insertable", "interfacebio_1_1ranges_1_1back__insertable.html", null ],
    [ "back_insertable_with", "interfacebio_1_1ranges_1_1back__insertable__with.html", null ],
    [ "builtin_character", "interfacebio_1_1meta_1_1builtin__character.html", null ],
    [ "const_iterable_range", "interfacebio_1_1ranges_1_1const__iterable__range.html", null ],
    [ "constexpr_default_initializable", "interfacebio_1_1meta_1_1constexpr__default__initializable.html", "interfacebio_1_1meta_1_1constexpr__default__initializable" ],
    [ "decays_to", "interfacebio_1_1meta_1_1decays__to.html", null ],
    [ "different_from", "interfacebio_1_1meta_1_1different__from.html", null ],
    [ "floating_point", "interfacebio_1_1meta_1_1floating__point.html", null ],
    [ "nonint_character", "interfacebio_1_1meta_1_1nonint__character.html", null ],
    [ "nucleotide_alphabet", "interfacebio_1_1alphabet_1_1nucleotide__alphabet.html", null ],
    [ "one_of", "interfacebio_1_1meta_1_1one__of.html", null ],
    [ "pair_like", "interfacebio_1_1meta_1_1pair__like.html", "interfacebio_1_1meta_1_1pair__like" ],
    [ "quality_alphabet", "interfacebio_1_1alphabet_1_1quality__alphabet.html", null ],
    [ "range_compatible", "interfacebio_1_1ranges_1_1range__compatible.html", null ],
    [ "semialphabet", "interfacebio_1_1alphabet_1_1semialphabet.html", null ],
    [ "standard_layout", "interfacebio_1_1meta_1_1standard__layout.html", null ],
    [ "template_specialisation_of", "interfacebio_1_1meta_1_1template__specialisation__of.html", null ],
    [ "transformation_trait", "interfacebio_1_1meta_1_1transformation__trait.html", null ],
    [ "trivial", "interfacebio_1_1meta_1_1trivial.html", null ],
    [ "trivially_copyable", "interfacebio_1_1meta_1_1trivially__copyable.html", null ],
    [ "trivially_destructible", "interfacebio_1_1meta_1_1trivially__destructible.html", null ],
    [ "tuple_like", "interfacebio_1_1meta_1_1tuple__like.html", "interfacebio_1_1meta_1_1tuple__like" ],
    [ "unary_type_trait", "interfacebio_1_1meta_1_1unary__type__trait.html", null ],
    [ "weakly_assignable_from", "interfacebio_1_1meta_1_1weakly__assignable__from.html", null ],
    [ "weakly_equality_comparable_with", "interfacebio_1_1meta_1_1weakly__equality__comparable__with.html", null ],
    [ "weakly_ordered_with", "interfacebio_1_1meta_1_1weakly__ordered__with.html", null ],
    [ "writable_alphabet", "interfacebio_1_1alphabet_1_1writable__alphabet.html", null ],
    [ "writable_quality_alphabet", "interfacebio_1_1alphabet_1_1writable__quality__alphabet.html", null ],
    [ "writable_semialphabet", "interfacebio_1_1alphabet_1_1writable__semialphabet.html", null ]
];