var searchData=
[
  ['va_5flist_1863',['va_list',['https://en.cppreference.com/w/cpp/utility/variadic/va_list.html',0,'']]],
  ['valarray_1864',['valarray',['https://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std::valarray'],['https://en.cppreference.com/w/cpp/header/valarray.html',0,'(Global Namespace)']]],
  ['valid_1865',['valid',['https://en.cppreference.com/w/cpp/thread/shared_future/valid.html',0,'std::shared_future::valid()'],['https://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',0,'std::packaged_task::valid()'],['https://en.cppreference.com/w/cpp/thread/future/valid.html',0,'std::future::valid()']]],
  ['value_1866',['value',['https://en.cppreference.com/w/cpp/error/error_condition/value.html',0,'std::error_condition::value()'],['https://en.cppreference.com/w/cpp/regex/regex_traits/value.html',0,'std::regex_traits::value()'],['https://en.cppreference.com/w/cpp/utility/optional/value.html',0,'std::optional::value()'],['https://en.cppreference.com/w/cpp/experimental/optional/value.html',0,'std::experimental::optional::value()'],['https://en.cppreference.com/w/cpp/error/error_code/value.html',0,'std::error_code::value()']]],
  ['value_5fcomp_1867',['value_comp',['https://en.cppreference.com/w/cpp/container/map/value_comp.html',0,'std::pmr::map::value_comp()'],['https://en.cppreference.com/w/cpp/container/map/value_comp.html',0,'std::map::value_comp()'],['https://en.cppreference.com/w/cpp/container/multimap/value_comp.html',0,'std::multimap::value_comp()'],['https://en.cppreference.com/w/cpp/container/multiset/value_comp.html',0,'std::multiset::value_comp()'],['https://en.cppreference.com/w/cpp/container/multimap/value_comp.html',0,'std::pmr::multimap::value_comp()'],['https://en.cppreference.com/w/cpp/container/multiset/value_comp.html',0,'std::pmr::multiset::value_comp()'],['https://en.cppreference.com/w/cpp/container/set/value_comp.html',0,'std::pmr::set::value_comp()'],['https://en.cppreference.com/w/cpp/container/set/value_comp.html',0,'std::set::value_comp()']]],
  ['value_5fcompare_1868',['value_compare',['https://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::map::value_compare'],['https://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::multimap::value_compare'],['https://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::pmr::map::value_compare'],['https://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::pmr::multimap::value_compare']]],
  ['value_5for_1869',['value_or',['https://en.cppreference.com/w/cpp/experimental/optional/value_or.html',0,'std::experimental::optional::value_or()'],['https://en.cppreference.com/w/cpp/utility/optional/value_or.html',0,'std::optional::value_or()']]],
  ['value_5ftype_1870',['value_type',['../structbio_1_1value__type.html',1,'bio::value_type&lt; t &gt;'],['../classbio_1_1concatenated__sequences.html#a5866e5af0357a11c9641e3d55ceade1a',1,'bio::concatenated_sequences::value_type()'],['../classbio_1_1aligned__allocator.html#adbfa49fe12ac3b71747af792543547c1',1,'bio::aligned_allocator::value_type()'],['../classbio_1_1bitcompressed__vector.html#ac9ee67bf9f36119e001763eee14e3e60',1,'bio::bitcompressed_vector::value_type()'],['../classbio_1_1dynamic__bitset.html#a592567f47c452fc8d6a0a10d8173e3e1',1,'bio::dynamic_bitset::value_type()'],['../classbio_1_1small__vector.html#a9da6b33bf009e04a1a11eaa81adeb8f2',1,'bio::small_vector::value_type()']]],
  ['value_5ftype_5ft_1871',['value_type_t',['../group__type__traits.html#ga5e8cde375522d7d61cf86837e0b0dacd',1,'bio']]],
  ['valueless_5fby_5fexception_1872',['valueless_by_exception',['https://en.cppreference.com/w/cpp/utility/variant/valueless_by_exception.html',0,'std::variant']]],
  ['variant_1873',['variant',['https://en.cppreference.com/w/cpp/utility/variant.html',0,'std::variant'],['https://en.cppreference.com/w/cpp/header/variant.html',0,'(Global Namespace)'],['https://en.cppreference.com/w/cpp/utility/variant/variant.html',0,'std::variant::variant()']]],
  ['variant_5falternative_1874',['variant_alternative',['https://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',0,'std']]],
  ['variant_5falternative_5ft_1875',['variant_alternative_t',['https://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',0,'std']]],
  ['variant_5fsize_1876',['variant_size',['https://en.cppreference.com/w/cpp/utility/variant/variant_size.html',0,'std']]],
  ['vector_1877',['vector',['https://en.cppreference.com/w/cpp/container/vector.html',0,'std::pmr::vector'],['https://en.cppreference.com/w/cpp/container/vector.html',0,'std::vector'],['https://en.cppreference.com/w/cpp/header/vector.html',0,'(Global Namespace)'],['https://en.cppreference.com/w/cpp/container/vector/vector.html',0,'std::pmr::vector::vector()'],['https://en.cppreference.com/w/cpp/container/vector/vector.html',0,'std::vector::vector()']]],
  ['vector_3c_20typename_20inner_5ftype_3a_3asize_5ftype_20_3e_1878',['vector&lt; typename inner_type::size_type &gt;',['https://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['version_1879',['version',['https://en.cppreference.com/w/cpp/header/version.html',0,'']]],
  ['version_2ehpp_1880',['version.hpp',['../version_8hpp.html',1,'']]],
  ['views_1881',['Views',['../group__views.html',1,'']]],
  ['void_5ft_1882',['void_t',['https://en.cppreference.com/w/cpp/types/void_t.html',0,'std']]]
];
