var searchData=
[
  ['back_5finsert_5fiterator_0',['back_insert_iterator',['https://en.cppreference.com/w/cpp/iterator/back_insert_iterator.html',0,'std']]],
  ['back_5finsertable_1',['back_insertable',['../interfacebio_1_1ranges_1_1back__insertable.html',1,'']]],
  ['back_5finsertable_5fwith_2',['back_insertable_with',['../interfacebio_1_1ranges_1_1back__insertable__with.html',1,'']]],
  ['bad_5falloc_3',['bad_alloc',['https://en.cppreference.com/w/cpp/memory/new/bad_alloc.html',0,'std']]],
  ['bad_5fany_5fcast_4',['bad_any_cast',['https://en.cppreference.com/w/cpp/utility/any/bad_any_cast.html',0,'std::bad_any_cast'],['https://en.cppreference.com/w/cpp/experimental/any/bad_any_cast.html',0,'std::experimental::bad_any_cast']]],
  ['bad_5farray_5fnew_5flength_5',['bad_array_new_length',['https://en.cppreference.com/w/cpp/memory/new/bad_array_new_length.html',0,'std']]],
  ['bad_5fcast_6',['bad_cast',['https://en.cppreference.com/w/cpp/types/bad_cast.html',0,'std']]],
  ['bad_5fexception_7',['bad_exception',['https://en.cppreference.com/w/cpp/error/bad_exception.html',0,'std']]],
  ['bad_5ffunction_5fcall_8',['bad_function_call',['https://en.cppreference.com/w/cpp/utility/functional/bad_function_call.html',0,'std']]],
  ['bad_5foptional_5faccess_9',['bad_optional_access',['https://en.cppreference.com/w/cpp/utility/optional/bad_optional_access.html',0,'std::bad_optional_access'],['https://en.cppreference.com/w/cpp/experimental/optional/bad_optional_access.html',0,'std::experimental::bad_optional_access']]],
  ['bad_5ftypeid_10',['bad_typeid',['https://en.cppreference.com/w/cpp/types/bad_typeid.html',0,'std']]],
  ['bad_5fvariant_5faccess_11',['bad_variant_access',['https://en.cppreference.com/w/cpp/utility/variant/bad_variant_access.html',0,'std']]],
  ['bad_5fweak_5fptr_12',['bad_weak_ptr',['https://en.cppreference.com/w/cpp/memory/bad_weak_ptr.html',0,'std']]],
  ['barrier_13',['barrier',['https://en.cppreference.com/w/cpp/thread/barrier.html',0,'std::barrier'],['https://en.cppreference.com/w/cpp/experimental/barrier.html',0,'std::experimental::barrier']]],
  ['base_14',['base',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20aa10li_2c_20size_2c_20char_20_3e_15',['base&lt; aa10li, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20aa10murphy_2c_20size_2c_20char_20_3e_16',['base&lt; aa10murphy, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20aa20_2c_20size_2c_20char_20_3e_17',['base&lt; aa20, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20aa27_2c_20size_2c_20char_20_3e_18',['base&lt; aa27, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20cigar_2c_281_20_2a_2e_2e_2e_20_2asize_3c_20component_5ftypes_20_3e_29_2c_20void_20_3e_19',['base&lt; cigar,(1 *... *size&lt; component_types &gt;), void &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20cigar_5fop_2c_209_2c_20char_20_3e_20',['base&lt; cigar_op, 9, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20derived_5ftype_2c_201ul_2c_20char_5ft_20_3e_21',['base&lt; derived_type, 1ul, char_t &gt;',['../classbio_1_1alphabet_1_1base_3_01derived__type_00_011ul_00_01char__t_01_4.html',1,'bio::alphabet']]],
  ['base_3c_20derived_5ftype_2c_20size_2c_20char_20_3e_22',['base&lt; derived_type, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20derived_5ftype_2c_281_20_2a_2e_2e_2e_20_2asize_3c_20component_5ftypes_20_3e_29_2c_20void_20_3e_23',['base&lt; derived_type,(1 *... *size&lt; component_types &gt;), void &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20dna15_2c_20size_2c_20char_20_3e_24',['base&lt; dna15, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20dna16sam_2c_20size_2c_20char_20_3e_25',['base&lt; dna16sam, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20dna4_2c_20size_2c_20char_20_3e_26',['base&lt; dna4, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20dna5_2c_20size_2c_20char_20_3e_27',['base&lt; dna5, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20gap_2c_201ull_2c_20char_20_3e_28',['base&lt; gap, 1ull, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20mask_2c_202_2c_20void_20_3e_29',['base&lt; mask, 2, void &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20masked_3c_20sequence_5falphabet_5ft_20_3e_2c_281_20_2a_2e_2e_2e_20_2asize_3c_20component_5ftypes_20_3e_29_2c_20void_20_3e_30',['base&lt; masked&lt; sequence_alphabet_t &gt;,(1 *... *size&lt; component_types &gt;), void &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20phred42_2c_20size_2c_20char_20_3e_31',['base&lt; phred42, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20phred63_2c_20size_2c_20char_20_3e_32',['base&lt; phred63, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20phred68legacy_2c_20size_2c_20char_20_3e_33',['base&lt; phred68legacy, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20qualified_3c_20sequence_5falphabet_5ft_2c_20quality_5falphabet_5ft_20_3e_2c_281_20_2a_2e_2e_2e_20_2asize_3c_20component_5ftypes_20_3e_29_2c_20void_20_3e_34',['base&lt; qualified&lt; sequence_alphabet_t, quality_alphabet_t &gt;,(1 *... *size&lt; component_types &gt;), void &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20rna15_2c_20size_2c_20char_20_3e_35',['base&lt; rna15, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20rna4_2c_20size_2c_20char_20_3e_36',['base&lt; rna4, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20rna5_2c_20size_2c_20char_20_3e_37',['base&lt; rna5, size, char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20semialphabet_5fany_3c_20size_5f_20_3e_2c_20size_5f_2c_20void_20_3e_38',['base&lt; semialphabet_any&lt; size_ &gt;, size_, void &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['base_3c_20variant_3c_20alternative_5ftypes_2e_2e_2e_20_3e_2c_28static_5fcast_3c_20size_5ft_20_3e_28size_3c_20alternative_5ftypes_20_3e_29_2b_2e_2e_2e_29_2c_20char_20_3e_39',['base&lt; variant&lt; alternative_types... &gt;,(static_cast&lt; size_t &gt;(size&lt; alternative_types &gt;)+...), char &gt;',['../classbio_1_1alphabet_1_1base.html',1,'bio::alphabet']]],
  ['basic_5fcommon_5freference_40',['basic_common_reference',['https://en.cppreference.com/w/cpp/types/common_reference.html',0,'std']]],
  ['basic_5ffilebuf_41',['basic_filebuf',['https://en.cppreference.com/w/cpp/io/basic_filebuf.html',0,'std']]],
  ['basic_5fformat_5farg_42',['basic_format_arg',['https://en.cppreference.com/w/cpp/utility/format/basic_format_arg.html',0,'std']]],
  ['basic_5fformat_5fargs_43',['basic_format_args',['https://en.cppreference.com/w/cpp/utility/format/basic_format_args.html',0,'std']]],
  ['basic_5fformat_5fcontext_44',['basic_format_context',['https://en.cppreference.com/w/cpp/utility/format/basic_format_context.html',0,'std']]],
  ['basic_5fformat_5fparse_5fcontext_45',['basic_format_parse_context',['https://en.cppreference.com/w/cpp/utility/format/basic_format_parse_context.html',0,'std']]],
  ['basic_5ffstream_46',['basic_fstream',['https://en.cppreference.com/w/cpp/io/basic_fstream.html',0,'std']]],
  ['basic_5fifstream_47',['basic_ifstream',['https://en.cppreference.com/w/cpp/io/basic_ifstream.html',0,'std']]],
  ['basic_5fios_48',['basic_ios',['https://en.cppreference.com/w/cpp/io/basic_ios.html',0,'std']]],
  ['basic_5fiostream_49',['basic_iostream',['https://en.cppreference.com/w/cpp/io/basic_iostream.html',0,'std']]],
  ['basic_5fistream_50',['basic_istream',['https://en.cppreference.com/w/cpp/io/basic_istream.html',0,'std']]],
  ['basic_5fistringstream_51',['basic_istringstream',['https://en.cppreference.com/w/cpp/io/basic_istringstream.html',0,'std']]],
  ['basic_5fofstream_52',['basic_ofstream',['https://en.cppreference.com/w/cpp/io/basic_ofstream.html',0,'std']]],
  ['basic_5fostream_53',['basic_ostream',['https://en.cppreference.com/w/cpp/io/basic_ostream.html',0,'std']]],
  ['basic_5fostringstream_54',['basic_ostringstream',['https://en.cppreference.com/w/cpp/io/basic_ostringstream.html',0,'std']]],
  ['basic_5fosyncstream_55',['basic_osyncstream',['https://en.cppreference.com/w/cpp/io/basic_osyncstream.html',0,'std']]],
  ['basic_5fregex_56',['basic_regex',['https://en.cppreference.com/w/cpp/regex/basic_regex.html',0,'std']]],
  ['basic_5fstreambuf_57',['basic_streambuf',['https://en.cppreference.com/w/cpp/io/basic_streambuf.html',0,'std']]],
  ['basic_5fstring_58',['basic_string',['https://en.cppreference.com/w/cpp/string/basic_string.html',0,'std']]],
  ['basic_5fstring_5fview_59',['basic_string_view',['https://en.cppreference.com/w/cpp/string/basic_string_view.html',0,'std::basic_string_view'],['https://en.cppreference.com/w/cpp/experimental/basic_string_view.html',0,'std::experimental::basic_string_view']]],
  ['basic_5fstringbuf_60',['basic_stringbuf',['https://en.cppreference.com/w/cpp/io/basic_stringbuf.html',0,'std']]],
  ['basic_5fstringstream_61',['basic_stringstream',['https://en.cppreference.com/w/cpp/io/basic_stringstream.html',0,'std']]],
  ['basic_5fsyncbuf_62',['basic_syncbuf',['https://en.cppreference.com/w/cpp/io/basic_syncbuf.html',0,'std']]],
  ['bernoulli_5fdistribution_63',['bernoulli_distribution',['https://en.cppreference.com/w/cpp/numeric/random/bernoulli_distribution.html',0,'std']]],
  ['bidirectional_5fiterator_5ftag_64',['bidirectional_iterator_tag',['https://en.cppreference.com/w/cpp/iterator/iterator_tags.html',0,'std']]],
  ['binary_5ffunction_65',['binary_function',['https://en.cppreference.com/w/cpp/utility/functional/binary_function.html',0,'std']]],
  ['binary_5fnegate_66',['binary_negate',['https://en.cppreference.com/w/cpp/utility/functional/binary_negate.html',0,'std']]],
  ['binary_5fsemaphore_67',['binary_semaphore',['https://en.cppreference.com/w/cpp/thread/counting_semaphore.html',0,'std']]],
  ['binder1st_68',['binder1st',['https://en.cppreference.com/w/cpp/utility/functional/binder12.html',0,'std']]],
  ['binder2nd_69',['binder2nd',['https://en.cppreference.com/w/cpp/utility/functional/binder12.html',0,'std']]],
  ['binomial_5fdistribution_70',['binomial_distribution',['https://en.cppreference.com/w/cpp/numeric/random/binomial_distribution.html',0,'std']]],
  ['bit_5fand_71',['bit_and',['https://en.cppreference.com/w/cpp/utility/functional/bit_and.html',0,'std']]],
  ['bit_5fnot_72',['bit_not',['https://en.cppreference.com/w/cpp/utility/functional/bit_not.html',0,'std']]],
  ['bit_5for_73',['bit_or',['https://en.cppreference.com/w/cpp/utility/functional/bit_or.html',0,'std']]],
  ['bit_5fxor_74',['bit_xor',['https://en.cppreference.com/w/cpp/utility/functional/bit_xor.html',0,'std']]],
  ['bitcompressed_5fvector_75',['bitcompressed_vector',['../classbio_1_1ranges_1_1bitcompressed__vector.html',1,'bio::ranges']]],
  ['bitset_76',['bitset',['https://en.cppreference.com/w/cpp/utility/bitset.html',0,'std']]],
  ['bool_5fconstant_77',['bool_constant',['https://en.cppreference.com/w/cpp/types/integral_constant.html',0,'std']]],
  ['boyer_5fmoore_5fhorspool_5fsearcher_78',['boyer_moore_horspool_searcher',['https://en.cppreference.com/w/cpp/utility/functional/boyer_moore_horspool_searcher.html',0,'std::boyer_moore_horspool_searcher'],['https://en.cppreference.com/w/cpp/experimental/boyer_moore_horspool_searcher.html',0,'std::experimental::boyer_moore_horspool_searcher']]],
  ['boyer_5fmoore_5fsearcher_79',['boyer_moore_searcher',['https://en.cppreference.com/w/cpp/utility/functional/boyer_moore_searcher.html',0,'std::boyer_moore_searcher'],['https://en.cppreference.com/w/cpp/experimental/boyer_moore_searcher.html',0,'std::experimental::boyer_moore_searcher']]],
  ['builtin_5fcharacter_80',['builtin_character',['../interfacebio_1_1meta_1_1builtin__character.html',1,'']]],
  ['byte_81',['byte',['https://en.cppreference.com/w/cpp/types/byte.html',0,'std']]]
];
