var searchData=
[
  ['aa10li_2008',['aa10li',['../classbio_1_1alphabet_1_1aa10li.html',1,'bio::alphabet']]],
  ['aa10murphy_2009',['aa10murphy',['../classbio_1_1alphabet_1_1aa10murphy.html',1,'bio::alphabet']]],
  ['aa20_2010',['aa20',['../classbio_1_1alphabet_1_1aa20.html',1,'bio::alphabet']]],
  ['aa27_2011',['aa27',['../classbio_1_1alphabet_1_1aa27.html',1,'bio::alphabet']]],
  ['add_5fconst_2012',['add_const',['https://en.cppreference.com/w/cpp/types/add_cv.html',0,'std']]],
  ['add_5fconst_5ft_2013',['add_const_t',['https://en.cppreference.com/w/cpp/types/add_cv.html',0,'std']]],
  ['add_5fcv_2014',['add_cv',['https://en.cppreference.com/w/cpp/types/add_cv.html',0,'std']]],
  ['add_5fcv_5ft_2015',['add_cv_t',['https://en.cppreference.com/w/cpp/types/add_cv.html',0,'std']]],
  ['add_5flvalue_5freference_2016',['add_lvalue_reference',['https://en.cppreference.com/w/cpp/types/add_reference.html',0,'std']]],
  ['add_5flvalue_5freference_5ft_2017',['add_lvalue_reference_t',['https://en.cppreference.com/w/cpp/types/add_reference.html',0,'std']]],
  ['add_5fpointer_2018',['add_pointer',['https://en.cppreference.com/w/cpp/types/add_pointer.html',0,'std']]],
  ['add_5fpointer_5ft_2019',['add_pointer_t',['https://en.cppreference.com/w/cpp/types/add_pointer.html',0,'std']]],
  ['add_5frvalue_5freference_2020',['add_rvalue_reference',['https://en.cppreference.com/w/cpp/types/add_reference.html',0,'std']]],
  ['add_5frvalue_5freference_5ft_2021',['add_rvalue_reference_t',['https://en.cppreference.com/w/cpp/types/add_reference.html',0,'std']]],
  ['add_5fvolatile_2022',['add_volatile',['https://en.cppreference.com/w/cpp/types/add_cv.html',0,'std']]],
  ['add_5fvolatile_5ft_2023',['add_volatile_t',['https://en.cppreference.com/w/cpp/types/add_cv.html',0,'std']]],
  ['adopt_5flock_5ft_2024',['adopt_lock_t',['https://en.cppreference.com/w/cpp/thread/lock_tag_t.html',0,'std']]],
  ['align_5fval_5ft_2025',['align_val_t',['https://en.cppreference.com/w/cpp/memory/new/align_val_t.html',0,'std']]],
  ['aligned_5fallocator_2026',['aligned_allocator',['../classbio_1_1ranges_1_1aligned__allocator.html',1,'bio::ranges']]],
  ['aligned_5fstorage_2027',['aligned_storage',['https://en.cppreference.com/w/cpp/types/aligned_storage.html',0,'std']]],
  ['aligned_5fstorage_5ft_2028',['aligned_storage_t',['https://en.cppreference.com/w/cpp/types/aligned_storage.html',0,'std']]],
  ['aligned_5funion_2029',['aligned_union',['https://en.cppreference.com/w/cpp/types/aligned_union.html',0,'std']]],
  ['aligned_5funion_5ft_2030',['aligned_union_t',['https://en.cppreference.com/w/cpp/types/aligned_union.html',0,'std']]],
  ['alignment_5fof_2031',['alignment_of',['https://en.cppreference.com/w/cpp/types/alignment_of.html',0,'std']]],
  ['allocator_2032',['allocator',['https://en.cppreference.com/w/cpp/memory/allocator.html',0,'std']]],
  ['allocator_5farg_5ft_2033',['allocator_arg_t',['https://en.cppreference.com/w/cpp/memory/allocator_arg_t.html',0,'std']]],
  ['allocator_5ftraits_2034',['allocator_traits',['https://en.cppreference.com/w/cpp/memory/allocator_traits.html',0,'std']]],
  ['alphabet_2035',['alphabet',['../interfacebio_1_1alphabet_1_1alphabet.html',1,'']]],
  ['alphabet_5fbase_2036',['alphabet_base',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20alphabet_5fvariant_3c_20alternative_5ftypes_2e_2e_2e_20_3e_2c_28static_5fcast_3c_20size_5ft_20_3e_28size_3c_20alternative_5ftypes_20_3e_29_2b_2e_2e_2e_29_2c_20char_20_3e_2037',['alphabet_base&lt; alphabet_variant&lt; alternative_types... &gt;,(static_cast&lt; size_t &gt;(size&lt; alternative_types &gt;)+...), char &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20cigar_2c_281_20_2a_2e_2e_2e_20_2asize_3c_20component_5ftypes_20_3e_29_2c_20void_20_3e_2038',['alphabet_base&lt; cigar,(1 *... *size&lt; component_types &gt;), void &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20cigar_5fop_2c_209_2c_20char_20_3e_2039',['alphabet_base&lt; cigar_op, 9, char &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20derived_5ftype_2c_201ul_2c_20char_5ft_20_3e_2040',['alphabet_base&lt; derived_type, 1ul, char_t &gt;',['../classbio_1_1alphabet_1_1alphabet__base_3_01derived__type_00_011ul_00_01char__t_01_4.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20derived_5ftype_2c_20size_2c_20char_20_3e_2041',['alphabet_base&lt; derived_type, size, char &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20derived_5ftype_2c_281_20_2a_2e_2e_2e_20_2asize_3c_20component_5ftypes_20_3e_29_2c_20void_20_3e_2042',['alphabet_base&lt; derived_type,(1 *... *size&lt; component_types &gt;), void &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20gap_2c_201ull_2c_20char_20_3e_2043',['alphabet_base&lt; gap, 1ull, char &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20mask_2c_202_2c_20void_20_3e_2044',['alphabet_base&lt; mask, 2, void &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20masked_3c_20sequence_5falphabet_5ft_20_3e_2c_281_20_2a_2e_2e_2e_20_2asize_3c_20component_5ftypes_20_3e_29_2c_20void_20_3e_2045',['alphabet_base&lt; masked&lt; sequence_alphabet_t &gt;,(1 *... *size&lt; component_types &gt;), void &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20qualified_3c_20sequence_5falphabet_5ft_2c_20quality_5falphabet_5ft_20_3e_2c_281_20_2a_2e_2e_2e_20_2asize_3c_20component_5ftypes_20_3e_29_2c_20void_20_3e_2046',['alphabet_base&lt; qualified&lt; sequence_alphabet_t, quality_alphabet_t &gt;,(1 *... *size&lt; component_types &gt;), void &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fbase_3c_20semialphabet_5fany_3c_20size_5f_20_3e_2c_20size_5f_2c_20void_20_3e_2047',['alphabet_base&lt; semialphabet_any&lt; size_ &gt;, size_, void &gt;',['../classbio_1_1alphabet_1_1alphabet__base.html',1,'bio::alphabet']]],
  ['alphabet_5fproxy_2048',['alphabet_proxy',['../classbio_1_1alphabet_1_1alphabet__proxy.html',1,'bio::alphabet']]],
  ['alphabet_5fproxy_3c_20component_5fproxy_3c_20alphabet_5ftype_2c_20index_20_3e_2c_20alphabet_5ftype_20_3e_2049',['alphabet_proxy&lt; component_proxy&lt; alphabet_type, index &gt;, alphabet_type &gt;',['../classbio_1_1alphabet_1_1alphabet__proxy.html',1,'bio::alphabet']]],
  ['alphabet_5fproxy_3c_20reference_5fproxy_5ftype_2c_20alphabet_5ftype_20_3e_2050',['alphabet_proxy&lt; reference_proxy_type, alphabet_type &gt;',['../classbio_1_1alphabet_1_1alphabet__proxy.html',1,'bio::alphabet']]],
  ['alphabet_5ftuple_5fbase_2051',['alphabet_tuple_base',['../classbio_1_1alphabet_1_1alphabet__tuple__base.html',1,'bio::alphabet']]],
  ['alphabet_5ftuple_5fbase_3c_20cigar_2c_20uint32_5ft_2c_20cigar_5fop_20_3e_2052',['alphabet_tuple_base&lt; cigar, uint32_t, cigar_op &gt;',['../classbio_1_1alphabet_1_1alphabet__tuple__base.html',1,'bio::alphabet']]],
  ['alphabet_5ftuple_5fbase_3c_20masked_3c_20sequence_5falphabet_5ft_20_3e_2c_20sequence_5falphabet_5ft_2c_20mask_20_3e_2053',['alphabet_tuple_base&lt; masked&lt; sequence_alphabet_t &gt;, sequence_alphabet_t, mask &gt;',['../classbio_1_1alphabet_1_1alphabet__tuple__base.html',1,'bio::alphabet']]],
  ['alphabet_5ftuple_5fbase_3c_20qualified_3c_20sequence_5falphabet_5ft_2c_20quality_5falphabet_5ft_20_3e_2c_20sequence_5falphabet_5ft_2c_20quality_5falphabet_5ft_20_3e_2054',['alphabet_tuple_base&lt; qualified&lt; sequence_alphabet_t, quality_alphabet_t &gt;, sequence_alphabet_t, quality_alphabet_t &gt;',['../classbio_1_1alphabet_1_1alphabet__tuple__base.html',1,'bio::alphabet']]],
  ['alphabet_5fvariant_2055',['alphabet_variant',['../classbio_1_1alphabet_1_1alphabet__variant.html',1,'bio::alphabet']]],
  ['aminoacid_5falphabet_2056',['aminoacid_alphabet',['../interfacebio_1_1alphabet_1_1aminoacid__alphabet.html',1,'']]],
  ['aminoacid_5fbase_2057',['aminoacid_base',['../classbio_1_1alphabet_1_1aminoacid__base.html',1,'bio::alphabet']]],
  ['aminoacid_5fbase_3c_20aa10li_2c_2010_20_3e_2058',['aminoacid_base&lt; aa10li, 10 &gt;',['../classbio_1_1alphabet_1_1aminoacid__base.html',1,'bio::alphabet']]],
  ['aminoacid_5fbase_3c_20aa10murphy_2c_2010_20_3e_2059',['aminoacid_base&lt; aa10murphy, 10 &gt;',['../classbio_1_1alphabet_1_1aminoacid__base.html',1,'bio::alphabet']]],
  ['aminoacid_5fbase_3c_20aa20_2c_2020_20_3e_2060',['aminoacid_base&lt; aa20, 20 &gt;',['../classbio_1_1alphabet_1_1aminoacid__base.html',1,'bio::alphabet']]],
  ['aminoacid_5fbase_3c_20aa27_2c_2027_20_3e_2061',['aminoacid_base&lt; aa27, 27 &gt;',['../classbio_1_1alphabet_1_1aminoacid__base.html',1,'bio::alphabet']]],
  ['aminoacid_5fempty_5fbase_2062',['aminoacid_empty_base',['../structbio_1_1alphabet_1_1aminoacid__empty__base.html',1,'bio::alphabet']]],
  ['any_2063',['any',['https://en.cppreference.com/w/cpp/utility/any.html',0,'std::any'],['https://en.cppreference.com/w/cpp/experimental/any.html',0,'std::experimental::any']]],
  ['arithmetic_2064',['arithmetic',['../interfacebio_1_1meta_1_1arithmetic.html',1,'']]],
  ['array_2065',['array',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20bio_3a_3aalphabet_3a_3adna15_2c_20alphabet_5fsize_20_3e_2066',['array&lt; bio::alphabet::dna15, alphabet_size &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20bio_3a_3aalphabet_3a_3adna16sam_2c_20alphabet_5fsize_20_3e_2067',['array&lt; bio::alphabet::dna16sam, alphabet_size &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20bio_3a_3aalphabet_3a_3adna5_2c_20alphabet_5fsize_20_3e_2068',['array&lt; bio::alphabet::dna5, alphabet_size &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20bio_3a_3aalphabet_3a_3arna15_2c_20alphabet_5fsize_20_3e_2069',['array&lt; bio::alphabet::rna15, alphabet_size &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20bio_3a_3aalphabet_3a_3arna5_2c_20alphabet_5fsize_20_3e_2070',['array&lt; bio::alphabet::rna5, alphabet_size &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20bool_2c_20256_20_3e_2071',['array&lt; bool, 256 &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20char_5ftype_2c_20alphabet_5fsize_20_3e_2072',['array&lt; char_type, alphabet_size &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20phred_5ftype_2c_20alphabet_5fsize_20_3e_2073',['array&lt; phred_type, alphabet_size &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20rank_5ftype_2c_20256_20_3e_2074',['array&lt; rank_type, 256 &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20rank_5ftype_2c_20component_5flist_3a_3asize_28_29_3e_2075',['array&lt; rank_type, component_list::size()&gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20rank_5ftype_2c_20meta_3a_3adetail_3a_3asize_5fin_5fvalues_5fv_3c_20char_5ftype_20_3e_20_3e_2076',['array&lt; rank_type, meta::detail::size_in_values_v&lt; char_type &gt; &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20rank_5ftype_2c_20sizeof_2e_2e_2e_28alternative_5ftypes_29_2b1_20_3e_2077',['array&lt; rank_type, sizeof...(alternative_types)+1 &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20value_5ftype_2c_20capacity_5f_20_3e_2078',['array&lt; value_type, capacity_ &gt;',['https://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['assign_5fchar_5fto_2079',['assign_char_to',['../structbio_1_1alphabet_1_1cpo_1_1assign__char__to.html',1,'bio::alphabet::cpo']]],
  ['assign_5fphred_5fto_2080',['assign_phred_to',['../structbio_1_1alphabet_1_1cpo_1_1assign__phred__to.html',1,'bio::alphabet::cpo']]],
  ['assign_5frank_5fto_2081',['assign_rank_to',['../structbio_1_1alphabet_1_1cpo_1_1assign__rank__to.html',1,'bio::alphabet::cpo']]],
  ['atomic_2082',['atomic',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fbool_2083',['atomic_bool',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fchar16_5ft_2084',['atomic_char16_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fchar32_5ft_2085',['atomic_char32_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fflag_2086',['atomic_flag',['https://en.cppreference.com/w/cpp/atomic/atomic_flag.html',0,'std']]],
  ['atomic_5fint_2087',['atomic_int',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint16_5ft_2088',['atomic_int16_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint32_5ft_2089',['atomic_int32_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint64_5ft_2090',['atomic_int64_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint8_5ft_2091',['atomic_int8_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint_5ffast16_5ft_2092',['atomic_int_fast16_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint_5ffast32_5ft_2093',['atomic_int_fast32_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint_5ffast64_5ft_2094',['atomic_int_fast64_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint_5ffast8_5ft_2095',['atomic_int_fast8_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint_5fleast16_5ft_2096',['atomic_int_least16_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint_5fleast32_5ft_2097',['atomic_int_least32_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint_5fleast64_5ft_2098',['atomic_int_least64_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fint_5fleast8_5ft_2099',['atomic_int_least8_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fintmax_5ft_2100',['atomic_intmax_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fintptr_5ft_2101',['atomic_intptr_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fllong_2102',['atomic_llong',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5flong_2103',['atomic_long',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fptrdiff_5ft_2104',['atomic_ptrdiff_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fref_2105',['atomic_ref',['https://en.cppreference.com/w/cpp/atomic/atomic_ref.html',0,'std']]],
  ['atomic_5fschar_2106',['atomic_schar',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fshort_2107',['atomic_short',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fsize_5ft_2108',['atomic_size_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuchar_2109',['atomic_uchar',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint_2110',['atomic_uint',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint16_5ft_2111',['atomic_uint16_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint32_5ft_2112',['atomic_uint32_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint64_5ft_2113',['atomic_uint64_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint8_5ft_2114',['atomic_uint8_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint_5ffast16_5ft_2115',['atomic_uint_fast16_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint_5ffast32_5ft_2116',['atomic_uint_fast32_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint_5ffast64_5ft_2117',['atomic_uint_fast64_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint_5ffast8_5ft_2118',['atomic_uint_fast8_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint_5fleast16_5ft_2119',['atomic_uint_least16_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint_5fleast32_5ft_2120',['atomic_uint_least32_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint_5fleast64_5ft_2121',['atomic_uint_least64_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuint_5fleast8_5ft_2122',['atomic_uint_least8_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuintmax_5ft_2123',['atomic_uintmax_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fuintptr_5ft_2124',['atomic_uintptr_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fullong_2125',['atomic_ullong',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fulong_2126',['atomic_ulong',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fushort_2127',['atomic_ushort',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['atomic_5fwchar_5ft_2128',['atomic_wchar_t',['https://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std']]],
  ['auto_5fptr_2129',['auto_ptr',['https://en.cppreference.com/w/cpp/memory/auto_ptr.html',0,'std']]]
];
