var searchData=
[
  ['valarray_0',['valarray',['https://en.cppreference.com/w/cpp/numeric/valarray/valarray.html',0,'std::valarray']]],
  ['valid_1',['valid',['https://en.cppreference.com/w/cpp/thread/future/valid.html',0,'std::future::valid()'],['https://en.cppreference.com/w/cpp/thread/shared_future/valid.html',0,'std::shared_future::valid()'],['https://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',0,'std::packaged_task::valid()']]],
  ['value_2',['value',['https://en.cppreference.com/w/cpp/error/error_code/value.html',0,'std::error_code::value()'],['https://en.cppreference.com/w/cpp/error/error_condition/value.html',0,'std::error_condition::value()'],['https://en.cppreference.com/w/cpp/experimental/optional/value.html',0,'std::experimental::optional::value()'],['https://en.cppreference.com/w/cpp/utility/optional/value.html',0,'std::optional::value()'],['https://en.cppreference.com/w/cpp/regex/regex_traits/value.html',0,'std::regex_traits::value()']]],
  ['value_5fcomp_3',['value_comp',['https://en.cppreference.com/w/cpp/container/map/value_comp.html',0,'std::map::value_comp()'],['https://en.cppreference.com/w/cpp/container/multimap/value_comp.html',0,'std::multimap::value_comp()'],['https://en.cppreference.com/w/cpp/container/multiset/value_comp.html',0,'std::multiset::value_comp()'],['https://en.cppreference.com/w/cpp/container/map/value_comp.html',0,'std::pmr::map::value_comp()'],['https://en.cppreference.com/w/cpp/container/multimap/value_comp.html',0,'std::pmr::multimap::value_comp()'],['https://en.cppreference.com/w/cpp/container/multiset/value_comp.html',0,'std::pmr::multiset::value_comp()'],['https://en.cppreference.com/w/cpp/container/set/value_comp.html',0,'std::pmr::set::value_comp()'],['https://en.cppreference.com/w/cpp/container/set/value_comp.html',0,'std::set::value_comp()']]],
  ['value_5fcompare_4',['value_compare',['https://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::pmr::multimap::value_compare::value_compare()'],['https://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::multimap::value_compare::value_compare()'],['https://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::map::value_compare::value_compare()'],['https://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::pmr::map::value_compare::value_compare()']]],
  ['value_5for_5',['value_or',['https://en.cppreference.com/w/cpp/experimental/optional/value_or.html',0,'std::experimental::optional::value_or()'],['https://en.cppreference.com/w/cpp/utility/optional/value_or.html',0,'std::optional::value_or()']]],
  ['valueless_5fby_5fexception_6',['valueless_by_exception',['https://en.cppreference.com/w/cpp/utility/variant/valueless_by_exception.html',0,'std::variant']]],
  ['variant_7',['variant',['../classbio_1_1alphabet_1_1variant.html#a98babde3a797c9184f92791759eafcda',1,'bio::alphabet::variant::variant(variant &amp;&amp;) noexcept=default'],['../classbio_1_1alphabet_1_1variant.html#a74c4e2c79579e2187b09d57c1067b4b1',1,'bio::alphabet::variant::variant(indirect_alternative_t const rhs) noexcept'],['../classbio_1_1alphabet_1_1variant.html#a74c4e2c79579e2187b09d57c1067b4b1',1,'bio::alphabet::variant::variant(indirect_alternative_t const rhs) noexcept'],['../classbio_1_1alphabet_1_1variant.html#ad6e1825e588a999abb294ea68a77aba3',1,'bio::alphabet::variant::variant(alternative_t const alternative) noexcept'],['../classbio_1_1alphabet_1_1variant.html#acc133df380faa92c41504c4657758e46',1,'bio::alphabet::variant::variant(variant const &amp;) noexcept=default'],['../classbio_1_1alphabet_1_1variant.html#a4ee0cb5dafbe21258dbad476779bf3f2',1,'bio::alphabet::variant::variant() noexcept=default'],['https://en.cppreference.com/w/cpp/utility/variant/variant.html',0,'std::variant::variant()']]],
  ['vector_8',['vector',['https://en.cppreference.com/w/cpp/container/vector/vector.html',0,'std::pmr::vector::vector()'],['https://en.cppreference.com/w/cpp/container/vector/vector.html',0,'std::vector::vector()']]],
  ['vector_29_9',['vector)',['https://en.cppreference.com/w/cpp/experimental/vector/erase.html',0,'std::experimental::erase(std::vector)()'],['https://en.cppreference.com/w/cpp/experimental/vector/erase_if.html',0,'std::experimental::erase_if(std::vector)()']]],
  ['view_10',['view',['../classbio_1_1ranges_1_1small__string.html#abd1fda7d48a5668ddaccf50cb3ac123c',1,'bio::ranges::small_string']]]
];
